sudo: required
os: windows
language: cpp

cache:
  directories:
    - $HOME/.ccache

git:
  quiet: true

env:
  global:    
    - ROS_REPO=ros
    - CMAKE_ARGS="-DENABLE_TESTS=ON"  

install:
  - choco feature disable -n=showDownloadProgress
  - cd ..
  - mkdir -p catkin_ws/src
  - mv opw_kinematics catkin_ws/src/
  - cd catkin_ws
  - choco source add -n=ros-win -s="https://roswin.azurewebsites.net/api/v2" --priority=1
  - choco install ros-melodic-ros_base -y --execution-timeout=0
  - cmd "/C $TRAVIS_BUILD_DIR/../catkin_ws/src/opw_kinematics/travis_ci_windows_install.bat"
  

script:
  - cmd "/C $TRAVIS_BUILD_DIR/../catkin_ws/src/opw_kinematics/travis_ci_windows.bat"
